apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: harryjung0330/authentication:0.0.1
        ports:
        - name: auth-port
          containerPort: 8011
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: test
        - name: jasypt.encryptor.password
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: jasypt-key
              optional: false
        - name: KAFKA_SERVER_DOMAIN
          value: kafka-service
        - name: KAFKA_SERVER_PORT
          value: "9092"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authentication-service
  name: authentication-service
spec:
  type: ClusterIP
  ports:
    - name: authentication-port
      port: 8000
      targetPort: auth-port
  selector:
    app: authentication