apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting
  labels:
    app: meeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeting
  template:
    metadata:
      labels:
        app: meeting
        version: "1"
    spec:
      containers:
      - name: meeting
        image: harryjung0330/meeting:LATEST
        ports:
        - name: meeting-port
          containerPort: 8016
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: test
        - name: jasypt.encryptor.password
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: jasypt-key
              optional: false 
        - name: KAFKA_SERVER_DOMAIN
          value: kafka-service
        - name: KAFKA_SERVER_PORT
          value: "9092"
        - name: SOCCER_GROUP_DOMAIN
          value: soccer-group-service
        - name: SOCCER_GROUP_PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meeting-service
  name: meeting-service
spec:
  type: ClusterIP
  ports:
    - name: meeting-port
      port: 8000
      targetPort: meeting-port
  selector:
    app: meeting