apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: harryjung0330/vote:0.0.2
        ports:
        - name: vote-port
          containerPort: 8015
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: test
        - name: jasypt.encryptor.password
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: jasypt-key
              optional: false 
        - name: KAFKA_SERVER_DOMAIN
          value: kafka-service
        - name: KAFKA_SERVER_PORT
          value: "9092"
        - name: SOCCER_GROUP_DOMAIN
          value: soccer-group-service
        - name: SOCCER_GROUP_PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-service
  name: vote-service
spec:
  type: ClusterIP
  ports:
    - name: vote-port
      port: 8000
      targetPort: vote-port
  selector:
    app: vote